version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29-node8-alpha

    branches:
      only:
        - master

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew clean
      - run: ./gradlew assembleRelease
      - run: ./gradlew bintrayUpload
